
apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  completions: 10
  template:
   spec:
    containers:
    - name: ubuntu
      image: ubuntu
      command: ["echo" ,"Hello"]
    restartPolicy: Never

