apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
   capacity:
    storage: 1Gi
    hostPath:
      path: /tmp/data
    accessModes:
      - ReadWriteOnce

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2
spec:
   capacity:
    storage: 500Mi
    hostPath:
      path: /tmp/data
    accessModes:
      - ReadWriteOnce

#kubectl apply -f persistentvol.yaml
#kubectl get pv 
      
