apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

#sudo kubectl apply -f pvclaim.yaml      
#sudo kubectl get pvc
